### ISSUE TITLE
Regular1DGrid does not handle decreasing grids

### ISSUE THREAD

**Issue by andrewgryan** [met-office-ocean/obsoper#4]
`obsoper.grid.Regular1DGrid` used by `obsoper.Operator` to search regular lon/lat grids fails to recognise dimensions that are descending.

The issue is due to the assumption that the zeroth element of the 1D grid is also the minimum value.

The work around at present is to reverse dimensions that are descending `x[:, ::-1, :]` but this is hardly user friendly.

**Comment by andrewgryan** [comment]
4e7e01822bb87fe7e5ceae7dd196845c60dc24e4 solves the issue by splitting the concept of minimum value, which for ascending grids is the same as the initial value, with the idea of an initial value. The initial value added to the signed grid spacing can be used to determine the point position in index space for both ascending/descending regular 1D grids.

**Comment by andrewgryan** [comment]
@chrispeq could you review change 4e7e018 which solves our issue with BSH interpolation?

**Comment by chrispeq** [comment]
I reviewed the changes, and this makes sense.  Changes approved.

**Comment by andrewgryan** [comment]
I merged this change back into the master branch with pull request #5.
